### ISSUE TITLE
Technische Spezifikation: Brunsmanns Vorschläge

### ISSUE THREAD

**Issue by FrederikHa** [Nope-Cardgame/Doku#6]
# 💭 Vorstellung/Wunsch
Das ERD soll um ein Unentschieden für das Turnier ergänzt werden

# 📈 Nutzen
Vervollständigung des Modells

# 🔗 Abhängigkeit

**Comment by XX123Fabian123XX** [comment]
Ich habe es so verstanden, dass wir für das Spiel ein Unentschieden speichern sollen. Wenn z.B. das Spiel sehr lange dauert, weil beide Spieler nie keine Karten mehr haben und dass man dafür dann eine Bedingung formuliert. Ein Unentschieden für das Turnier macht keinen Sinn.
